#!/bin/bash

if [[ ! -n "$DISABLE_WAYLAND" && -n "$WAYLAND_DISPLAY" ]]; then
  WAYLAND_OPTS="--enable-features=UseOzonePlatform --ozone-platform-hint=auto --enable-wayland-ime"
fi

exec $SNAP/dist-app/linux-unpacked/lemonade \
	--disable-dev-shm-usage \
	$WAYLAND_OPTS \
	--no-sandbox "$@"
